Code coverage configuration
vscode-org-mode/vscode-org-mode-fork pull request #11
Opened 2018-10-17 00:40 UTC by rpeshkov

Added code coverage configuration.

There are 3 types of reports currently generated:

- Text
- HTML
- LCOV

Samples:

![screen shot 2018-10-17 at 02 31 53](https://user-images.githubusercontent.com/701068/47054951-241d8400-d1b5-11e8-9c22-e8945c5408cd.png)

![screen shot 2018-10-17 at 02 31 40](https://user-images.githubusercontent.com/701068/47054958-2bdd2880-d1b5-11e8-83d9-db3b72796c16.png)

I didn't provide screenshot on how LCOV report look like, but it's very usable format that can be loaded into e.g. this extension https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters and you'll see code coverage in text editor gutters. Refer to readme of extension for details.

2018-10-17 02:54 UTC, AdrieanKhisbe requested changes
Awesome!

some minor change to be made though

2018-10-17 02:54 UTC, AdrieanKhisbe commented on package.json
> +        "decache": "^4.4.0",
the four new dependencies should be devDependencies

2018-10-17 03:19 UTC, AdrieanKhisbe commented
@rpeshkov Do you think whether it's possible to extract most of test/index.ts logic into a library to minimise set up of coverage of other extension, and keep the index simple?

2018-10-17 09:21 UTC, rpeshkov commented
> @rpeshkov Do you think whether it's possible to extract most of test/index.ts logic into a library to minimise set up of coverage of other extension, and keep the index simple?

I'm not sure, need to check this. I'll try to do this today in the evening.

2018-10-17 09:35 UTC, AdrieanKhisbe commented
> > @rpeshkov Do you think whether it's possible to extract most of test/index.ts logic into a library to minimise set up of coverage of other extension, and keep the index simple?
> 
> I'm not sure, need to check this. I'll try to do this today in the evening.

There is no Hurry Roman, I was just evaluating the possibility as I have some personal vscode-extension. We won't delay merging of PR for this. 😃

2018-10-17 22:11 UTC, rpeshkov commented
@AdrieanKhisbe test runner extracted https://www.npmjs.com/package/vscode-coverage-test-runner

Everything works pretty well, changes to `index.ts`, compared to what it was initially, are minimal. Basically, only import path was changed.

Current NPM package is a little bit dummy, because I didn't bother with extracting configuration, so some paths are hardcoded for now, but I'll definitely make some updates later.

2018-10-18 02:54 UTC, AdrieanKhisbe commented
@rpeshkov Awesome work!

2018-10-18 03:51 UTC, AdrieanKhisbe commented
@rpeshkov I forked it and configure it a bit: https://github.com/rpeshkov/vscode-coverage-test-runner/pull/1

2024-02-22 13:02 UTC, closed without merging